version: "3.8"

services:
    ibf-api-service:
        image: gulfaraz/ibf-api-service
        ports:
            - 80:3000
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - api-service-root:/home/ibf/api-service
            - api-web-interface-root:/home/ibf/api-service/dist

    ibf-web-interface:
        image: gulfaraz/ibf-web-interface
        volumes:
            - api-web-interface-root:/home/node/app/www

volumes:
    api-service-root:
    api-web-interface-root:
