version: "3.8"

services:
    nginx:
        image: nginx
        command:
            '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload;
            done & nginx -g "daemon off;"'''
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/ibf-system.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/expires.conf:/etc/nginx/expires.conf
            - ./nginx/proxy_params:/etc/nginx/proxy_params
            - ibf-dashboard-root:/var/www/ibf-dashboard
        networks:
            - web-server-network
        restart: unless-stopped

    ibf-api-service:
        build:
            context: ./services/API-service
            args:
                - NODE_ENV=production
        image: rodekruis/ibf-api-service
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - NODE_ENV=production
            - SECRET=${SECRET}
            - RESET_SECRET=${RESET_SECRET}
        networks:
            - web-server-network
        depends_on:
            - ibf-geoserver

    ibf-dashboard:
        build:
            context: ./interfaces/IBF-dashboard
            args:
                - NG_PRODUCTION=true
                - NG_API_URL=${NG_API_URL}
                - NG_USE_SERVICE_WORKER=${NG_USE_SERVICE_WORKER}
                - NG_GEOSERVER_URL=${NG_GEOSERVER_URL}
                - NG_IBF_SYSTEM_VERSION=${NG_IBF_SYSTEM_VERSION}
        image: rodekruis/ibf-dashboard
        environment:
            - NG_PRODUCTION=true
            - NG_API_URL=${NG_API_URL}
            - NG_USE_SERVICE_WORKER=${NG_USE_SERVICE_WORKER}
            - NG_GEOSERVER_URL=${NG_GEOSERVER_URL}
            - NG_IBF_SYSTEM_VERSION=${NG_IBF_SYSTEM_VERSION}
        volumes:
            - ibf-dashboard-root:/home/node/app/www
        networks:
            - web-server-network

    ibf-pipeline:
        build: ./services/IBF-pipeline
        image: rodekruis/ibf-pipeline
        command: cron && tail -f /var/log/cron.log
        volumes:
            - pipeline-root:/home/ibf
        networks:
            - pipeline-network
        restart: unless-stopped

    ibf-geoserver:
        image: kartoza/geoserver
        volumes:
            - pipeline-geoserver:/opt/geoserver/data_dir/workspaces/ibf-system/ibf-pipeline
            - workspace-geoserver:/opt/geoserver/data_dir/workspaces/ibf-system
        networks:
            - web-server-network
            - pipeline-network
        restart: unless-stopped

volumes:
    ibf-dashboard-root:
    pipeline-root:
        driver_opts:
            type: bind
            device: /home/ibf-user/IBF-system/services/IBF-pipeline
            o: bind
    pipeline-geoserver:
        driver_opts:
            type: bind
            device: /home/ibf-user/IBF-system/services/IBF-pipeline/pipeline/data/raster
            o: bind
    workspace-geoserver:
        driver_opts:
            type: bind
            device: /home/ibf-user/IBF-system/services/IBF-pipeline/geoserver-workspaces/ibf-system
            o: bind

networks:
    web-server-network:
        driver: bridge
    pipeline-network:
        driver: bridge
