version: "3.8"

services:
    ibf-api-service:
        build: ./services/API-service
        ports:
            - 3000:3000
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - NODE_ENV=production
        volumes:
            - api-service-root:/home/ibf/api-service

    ibf-web-interface:
        build: ./interfaces/overview
        volumes:
            - api-web-interface-root:/home/node/app/www
        networks:
            - web-interface-network

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - api-web-interface-root:/var/www/ibf-web-interface
            - ./nginx/ibf-web-interface.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - ibf-web-interface
        networks:
            - web-interface-network
        restart: unless-stopped

volumes:
    api-service-root:
    api-web-interface-root:

networks:
    web-interface-network:
        driver: bridge
