version: "3.8"

services:
    ibf-api-service:
        build: ./services/API-service
        image: rodekruis/ibf-api-service
        ports:
            - 80:3000
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - NODE_ENV=production
            - SECRET=${SECRET}
            - NG_PRODUCTION=true
            - NG_API_URL=${NG_API_URL}
            - NG_USE_MOCK_DATA=${NG_USE_MOCK_DATA}
            - NG_USE_SERVICE_WORKER=${NG_USE_SERVICE_WORKER}
            - NG_DEFAULT_COUNTRY_CODE=${NG_DEFAULT_COUNTRY_CODE}
            - NG_GEOSERVER_URL=${NG_GEOSERVER_URL}
        volumes:
            - api-service-root:/home/ibf/api-service
            - web-interface-root:/home/ibf/api-service/www

    ibf-web-interface:
        build: ./interfaces/overview
        image: rodekruis/ibf-web-interface
        environment:
            - NG_PRODUCTION=true
            - NG_API_URL=${NG_API_URL}
            - NG_USE_MOCK_DATA=${NG_USE_MOCK_DATA}
            - NG_USE_SERVICE_WORKER=${NG_USE_SERVICE_WORKER}
            - NG_DEFAULT_COUNTRY_CODE=${NG_DEFAULT_COUNTRY_CODE}
            - NG_GEOSERVER_URL=${NG_GEOSERVER_URL}
        volumes:
            - web-interface-root:/home/node/app/www

    ibf-pipeline:
        build: ./services/IBF-pipeline
        image: rodekruis/ibf-pipeline
        restart: unless-stopped
        volumes:
            - pipeline-root:/home/ibf
            - pipeline-geoserver:/home/ibf/geoserver/geodata
        command: tail -f /dev/null

    ibf-geoserver:
        image: kartoza/geoserver
        restart: unless-stopped
        volumes:
            - pipeline-geoserver:/opt/geoserver/data_dir/workspaces/ibf-system/ibf-pipeline

volumes:
    api-service-root:
    web-interface-root:
    pipeline-root:
        driver_opts:
           type: none
           device: /home/IBF-system/services/IBF-pipeline
           o: bind
    pipeline-geoserver:

