name: "C.I. for service: API-service"

on:
    push:
        branches: [master]
        paths: "services/API-service/**"
    pull_request:
        branches: [master]
        paths: "services/API-service/**"

jobs:
    ibf-api-service:
        runs-on: ubuntu-latest

        env:
            DB_TYPE: ${{ secrets.DB_TYPE }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_DATABASE: ${{ secrets.DB_DATABASE }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            SECRET: ${{ secrets.SECRET }}

        strategy:
            matrix:
                node-version: [12.x]

        defaults:
            run:
                working-directory: "services/API-service"

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci --no-audit
            - run: npm run lint
            - run: npm test
            - run:
                  docker build . --file Dockerfile --tag
                  rodekruis/ibf-api-service:$(date +%s)
