name: "C.I. for service: IBF-pipeline"

on:
    push:
        branches: [master]
        paths: "services/IBF-pipeline/**"
    pull_request:
        branches: [master]
        paths: "services/IBF-pipeline/**"

jobs:
    ibf-pipeline:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [2.7]

        defaults:
            run:
                working-directory: "services/IBF-pipeline"

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint
            - name: Analysing the code with pylint
              run: |
                  pylint `ls -R|grep .py$|xargs`
            - run:
                  docker build . --file Dockerfile --tag
                  rodekruis/ibf-pipeline:$(date +%s)
